// BS45F3235.h
//	This file contains the definition of registers for
//		Holtek BS45F3235 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.2, 4
// Do not modify manually.

#ifndef _BS45F3235_H_
#define _BS45F3235_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __dmbp0 : 1;
	unsigned char : 7;
} __bp_bits;

typedef union {
	__bp_bits bits;
	__sfr_byte byte;
} __bp_type;

typedef struct {
	unsigned char : 7;
	unsigned char __stis : 1;
} __muxsel_bits;

typedef union {
	__muxsel_bits bits;
	__sfr_byte byte;
} __muxsel_type;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char : 2;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char : 3;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char : 6;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __clksel0 : 1;
	unsigned char __clksel1 : 1;
	unsigned char : 6;
} __pscr_bits;

typedef union {
	__pscr_bits bits;
	__sfr_byte byte;
} __pscr_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char : 1;
	unsigned char __lvrf : 1;
	unsigned char : 5;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char __vbgen : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __ints0 : 1;
	unsigned char __ints1 : 1;
	unsigned char : 6;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char : 7;
	unsigned char __isgen : 1;
} __idata_bits;

typedef union {
	__idata_bits bits;
	__sfr_byte byte;
} __idata_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char __umd : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char __utx8 : 1;
	unsigned char __urx8 : 1;
	unsigned char __utxbrk : 1;
	unsigned char __ustops : 1;
	unsigned char __uprt : 1;
	unsigned char __upren : 1;
	unsigned char __ubno : 1;
	unsigned char __uren : 1;
} __uucr1_bits;

typedef union {
	__uucr1_bits bits;
	__sfr_byte byte;
} __uucr1_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char : 1;
	unsigned char __sima0 : 1;
	unsigned char __sima1 : 1;
	unsigned char __sima2 : 1;
	unsigned char __sima3 : 1;
	unsigned char __sima4 : 1;
	unsigned char __sima5 : 1;
	unsigned char __sima6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __uteie : 1;
	unsigned char __utiie : 1;
	unsigned char __urie : 1;
	unsigned char __uwake : 1;
	unsigned char __uadden : 1;
	unsigned char __ubrgh : 1;
	unsigned char __urxen : 1;
	unsigned char __utxen : 1;
} __uucr2_bits;

typedef union {
	__uucr2_bits bits;
	__sfr_byte byte;
} __uucr2_type;

typedef struct {
	unsigned char __utxrx0 : 1;
	unsigned char __utxrx1 : 1;
	unsigned char __utxrx2 : 1;
	unsigned char __utxrx3 : 1;
	unsigned char __utxrx4 : 1;
	unsigned char __utxrx5 : 1;
	unsigned char __utxrx6 : 1;
	unsigned char __utxrx7 : 1;
} __utxr_rxr_bits;

typedef union {
	__utxr_rxr_bits bits;
	__sfr_byte byte;
} __utxr_rxr_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __ubrg0 : 1;
	unsigned char __ubrg1 : 1;
	unsigned char __ubrg2 : 1;
	unsigned char __ubrg3 : 1;
	unsigned char __ubrg4 : 1;
	unsigned char __ubrg5 : 1;
	unsigned char __ubrg6 : 1;
	unsigned char __ubrg7 : 1;
} __ubrg_bits;

typedef union {
	__ubrg_bits bits;
	__sfr_byte byte;
} __ubrg_type;

typedef struct {
	unsigned char __utxif : 1;
	unsigned char __utidle : 1;
	unsigned char __urxif : 1;
	unsigned char __uridle : 1;
	unsigned char __uoerr : 1;
	unsigned char __uferr : 1;
	unsigned char __unf : 1;
	unsigned char __uperr : 1;
} __uusr_bits;

typedef union {
	__uusr_bits bits;
	__sfr_byte byte;
} __uusr_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char : 2;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __inte : 1;
	unsigned char __opde : 1;
	unsigned char __ade : 1;
	unsigned char __intf : 1;
	unsigned char __opdf : 1;
	unsigned char __adf : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __stmpe : 1;
	unsigned char __stmae : 1;
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char __stmpf : 1;
	unsigned char __stmaf : 1;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __usime : 1;
	unsigned char : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __usimf : 1;
	unsigned char : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char : 5;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char : 5;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char : 5;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __strp0 : 1;
	unsigned char __strp1 : 1;
	unsigned char __strp2 : 1;
	unsigned char __ston : 1;
	unsigned char __stck0 : 1;
	unsigned char __stck1 : 1;
	unsigned char __stck2 : 1;
	unsigned char __stpau : 1;
} __stmc0_bits;

typedef union {
	__stmc0_bits bits;
	__sfr_byte byte;
} __stmc0_type;

typedef struct {
	unsigned char __stcclr : 1;
	unsigned char __stdpx : 1;
	unsigned char __stpol : 1;
	unsigned char __stoc : 1;
	unsigned char __stio0 : 1;
	unsigned char __stio1 : 1;
	unsigned char __stm0 : 1;
	unsigned char __stm1 : 1;
} __stmc1_bits;

typedef union {
	__stmc1_bits bits;
	__sfr_byte byte;
} __stmc1_type;

typedef struct {
	unsigned char __opdsw0 : 1;
	unsigned char __opdsw1 : 1;
	unsigned char __opdsw2 : 1;
	unsigned char __opdsw3 : 1;
	unsigned char __opdsw4 : 1;
	unsigned char __opdsw5 : 1;
	unsigned char __opdsw6 : 1;
	unsigned char __opdsw7 : 1;
} __opdswa_bits;

typedef union {
	__opdswa_bits bits;
	__sfr_byte byte;
} __opdswa_type;

typedef struct {
	unsigned char __opdsw8 : 1;
	unsigned char __opdsw9 : 1;
	unsigned char __opdsw10 : 1;
	unsigned char __opdsw11 : 1;
	unsigned char __opdsw12 : 1;
	unsigned char __opdsw13 : 1;
	unsigned char __opdsw14 : 1;
	unsigned char __opdsw15 : 1;
} __opdswb_bits;

typedef union {
	__opdswb_bits bits;
	__sfr_byte byte;
} __opdswb_type;

typedef struct {
	unsigned char __opdsw16 : 1;
	unsigned char __opdsw17 : 1;
	unsigned char __opdsw18 : 1;
	unsigned char __opdsw19 : 1;
	unsigned char __opdsw20 : 1;
	unsigned char __opdsw21 : 1;
	unsigned char __opdsw22 : 1;
	unsigned char __opdsw23 : 1;
} __opdswc_bits;

typedef union {
	__opdswc_bits bits;
	__sfr_byte byte;
} __opdswc_type;

typedef struct {
	unsigned char __opdsw24 : 1;
	unsigned char __opdsw25 : 1;
	unsigned char __opdsw26 : 1;
	unsigned char __opdsw27 : 1;
	unsigned char __opdsw28 : 1;
	unsigned char : 3;
} __opdswd_bits;

typedef union {
	__opdswd_bits bits;
	__sfr_byte byte;
} __opdswd_type;

typedef struct {
	unsigned char __opddeb0 : 1;
	unsigned char __opddeb1 : 1;
	unsigned char __opddeb2 : 1;
	unsigned char __opdints0 : 1;
	unsigned char __opdints1 : 1;
	unsigned char __opdcen : 1;
	unsigned char __opda0en : 1;
	unsigned char __opda1en : 1;
} __opdc0_bits;

typedef union {
	__opdc0_bits bits;
	__sfr_byte byte;
} __opdc0_type;

typedef struct {
	unsigned char __opda0bw : 1;
	unsigned char __opda1bw : 1;
	unsigned char __opdis0 : 1;
	unsigned char __opdis1 : 1;
	unsigned char __opdhys0 : 1;
	unsigned char __opdhys1 : 1;
	unsigned char __opd0o : 1;
	unsigned char __opd1o : 1;
} __opdc1_bits;

typedef union {
	__opdc1_bits bits;
	__sfr_byte byte;
} __opdc1_type;

typedef struct {
	unsigned char __opda0of0 : 1;
	unsigned char __opda0of1 : 1;
	unsigned char __opda0of2 : 1;
	unsigned char __opda0of3 : 1;
	unsigned char __opda0of4 : 1;
	unsigned char __opda0of5 : 1;
	unsigned char __opda0rsp : 1;
	unsigned char __opda0ofm : 1;
} __opda0cal_bits;

typedef union {
	__opda0cal_bits bits;
	__sfr_byte byte;
} __opda0cal_type;

typedef struct {
	unsigned char __opda1of0 : 1;
	unsigned char __opda1of1 : 1;
	unsigned char __opda1of2 : 1;
	unsigned char __opda1of3 : 1;
	unsigned char __opda1of4 : 1;
	unsigned char __opda1of5 : 1;
	unsigned char __opda1rsp : 1;
	unsigned char __opda1ofm : 1;
} __opda1cal_bits;

typedef union {
	__opda1cal_bits bits;
	__sfr_byte byte;
} __opda1cal_type;

typedef struct {
	unsigned char __opdcof0 : 1;
	unsigned char __opdcof1 : 1;
	unsigned char __opdcof2 : 1;
	unsigned char __opdcof3 : 1;
	unsigned char __opdcof4 : 1;
	unsigned char __opdcrsp : 1;
	unsigned char __opdcofm : 1;
	unsigned char __opdcout : 1;
} __opdccal_bits;

typedef union {
	__opdccal_bits bits;
	__sfr_byte byte;
} __opdccal_type;

typedef struct {
	unsigned char __sacs0 : 1;
	unsigned char __sacs1 : 1;
	unsigned char __sacs2 : 1;
	unsigned char __sacs3 : 1;
	unsigned char __adrfs : 1;
	unsigned char __adcen : 1;
	unsigned char __adbz : 1;
	unsigned char __start : 1;
} __sadc0_bits;

typedef union {
	__sadc0_bits bits;
	__sfr_byte byte;
} __sadc0_type;

typedef struct {
	unsigned char __sacks0 : 1;
	unsigned char __sacks1 : 1;
	unsigned char __sacks2 : 1;
	unsigned char : 1;
	unsigned char __sains0 : 1;
	unsigned char __sains1 : 1;
	unsigned char __sains2 : 1;
	unsigned char __sains3 : 1;
} __sadc1_bits;

typedef union {
	__sadc1_bits bits;
	__sfr_byte byte;
} __sadc1_type;

typedef struct {
	unsigned char __pgags0 : 1;
	unsigned char __pgags1 : 1;
	unsigned char __savrs0 : 1;
	unsigned char __savrs1 : 1;
	unsigned char __pgais : 1;
	unsigned char : 2;
	unsigned char __adpgaen : 1;
} __sadc2_bits;

typedef union {
	__sadc2_bits bits;
	__sfr_byte byte;
} __sadc2_type;

typedef struct {
	unsigned char __scsbs0 : 1;
	unsigned char __scsbs1 : 1;
	unsigned char __rxsdisdas0 : 1;
	unsigned char __rxsdisdas1 : 1;
	unsigned char __sckscls0 : 1;
	unsigned char __sckscls1 : 1;
	unsigned char : 2;
} __ifs_bits;

typedef union {
	__ifs_bits bits;
	__sfr_byte byte;
} __ifs_type;

typedef struct {
	unsigned char __eea0 : 1;
	unsigned char __eea1 : 1;
	unsigned char __eea2 : 1;
	unsigned char __eea3 : 1;
	unsigned char __eea4 : 1;
	unsigned char : 3;
} __eea_bits;

typedef union {
	__eea_bits bits;
	__sfr_byte byte;
} __eea_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1, 0x03);
DEFINE_SFR(__bp_type, __bp, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__muxsel_type, __muxsel, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__scc_type, __scc, 0x0b);
DEFINE_SFR(__hircc_type, __hircc, 0x0c);
DEFINE_SFR(__pscr_type, __pscr, 0x0d);
DEFINE_SFR(__tb0c_type, __tb0c, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__tb1c_type, __tb1c, 0x10);
DEFINE_SFR(__lvdc_type, __lvdc, 0x11);
DEFINE_SFR(__wdtc_type, __wdtc, 0x12);
DEFINE_SFR(__integ_type, __integ, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__idata_type, __idata, 0x18);
DEFINE_SFR(__simc0_type, __simc0, 0x19);
DEFINE_SFR(__simc1_type, __simc1, 0x1a);
DEFINE_SFR(__uucr1_type, __uucr1, 0x1a);
DEFINE_SFR(__simc2_type, __simc2, 0x1b);
DEFINE_SFR(__sima_type, __sima, 0x1b);
DEFINE_SFR(__uucr2_type, __uucr2, 0x1b);
DEFINE_SFR(__sfr_byte, __simd, 0x1c);
DEFINE_SFR(__utxr_rxr_type, __utxr_rxr, 0x1c);
DEFINE_SFR(__simtoc_type, __simtoc, 0x1d);
DEFINE_SFR(__ubrg_type, __ubrg, 0x1d);
DEFINE_SFR(__uusr_type, __uusr, 0x1e);
DEFINE_SFR(__pas0_type, __pas0, 0x1f);
DEFINE_SFR(__pas1_type, __pas1, 0x20);
DEFINE_SFR(__pbs0_type, __pbs0, 0x21);
DEFINE_SFR(__intc0_type, __intc0, 0x22);
DEFINE_SFR(__intc1_type, __intc1, 0x23);
DEFINE_SFR(__intc2_type, __intc2, 0x24);
DEFINE_SFR(__pb_type, __pb, 0x25);
DEFINE_SFR(__pbc_type, __pbc, 0x26);
DEFINE_SFR(__pbpu_type, __pbpu, 0x27);
DEFINE_SFR(__stmc0_type, __stmc0, 0x28);
DEFINE_SFR(__stmc1_type, __stmc1, 0x29);
DEFINE_SFR(__sfr_byte, __stmdl, 0x2a);
DEFINE_SFR(__sfr_byte, __stmdh, 0x2b);
DEFINE_SFR(__sfr_byte, __stmal, 0x2c);
DEFINE_SFR(__sfr_byte, __stmah, 0x2d);
DEFINE_SFR(__opdswa_type, __opdswa, 0x2e);
DEFINE_SFR(__opdswb_type, __opdswb, 0x2f);
DEFINE_SFR(__opdswc_type, __opdswc, 0x30);
DEFINE_SFR(__opdswd_type, __opdswd, 0x31);
DEFINE_SFR(__opdc0_type, __opdc0, 0x32);
DEFINE_SFR(__opdc1_type, __opdc1, 0x33);
DEFINE_SFR(__sfr_byte, __opdda, 0x34);
DEFINE_SFR(__opda0cal_type, __opda0cal, 0x35);
DEFINE_SFR(__opda1cal_type, __opda1cal, 0x36);
DEFINE_SFR(__opdccal_type, __opdccal, 0x37);
DEFINE_SFR(__sfr_byte, __sadol, 0x38);
DEFINE_SFR(__sfr_byte, __sadoh, 0x39);
DEFINE_SFR(__sadc0_type, __sadc0, 0x3a);
DEFINE_SFR(__sadc1_type, __sadc1, 0x3b);
DEFINE_SFR(__sadc2_type, __sadc2, 0x3c);
DEFINE_SFR(__ifs_type, __ifs, 0x3d);
DEFINE_SFR(__eea_type, __eea, 0x3e);
DEFINE_SFR(__sfr_byte, __eed, 0x3f);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);

#define _iar0     __iar0
#define _iar1     __iar1
#define _mp0      __mp0
#define _mp1      __mp1
#define _bp       __bp.byte
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _muxsel   __muxsel.byte
#define _status   __status.byte
#define _scc      __scc.byte
#define _hircc    __hircc.byte
#define _pscr     __pscr.byte
#define _tb0c     __tb0c.byte
#define _rstfc    __rstfc.byte
#define _tb1c     __tb1c.byte
#define _lvdc     __lvdc.byte
#define _wdtc     __wdtc.byte
#define _integ    __integ.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _idata    __idata.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _uucr1    __uucr1.byte
#define _simc2    __simc2.byte
#define _sima     __sima.byte
#define _uucr2    __uucr2.byte
#define _simd     __simd
#define _utxr_rxr __utxr_rxr.byte
#define _simtoc   __simtoc.byte
#define _ubrg     __ubrg.byte
#define _uusr     __uusr.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _stmc0    __stmc0.byte
#define _stmc1    __stmc1.byte
#define _stmdl    __stmdl
#define _stmdh    __stmdh
#define _stmal    __stmal
#define _stmah    __stmah
#define _opdswa   __opdswa.byte
#define _opdswb   __opdswb.byte
#define _opdswc   __opdswc.byte
#define _opdswd   __opdswd.byte
#define _opdc0    __opdc0.byte
#define _opdc1    __opdc1.byte
#define _opdda    __opdda
#define _opda0cal __opda0cal.byte
#define _opda1cal __opda1cal.byte
#define _opdccal  __opdccal.byte
#define _sadol    __sadol
#define _sadoh    __sadoh
#define _sadc0    __sadc0.byte
#define _sadc1    __sadc1.byte
#define _sadc2    __sadc2.byte
#define _ifs      __ifs.byte
#define _eea      __eea.byte
#define _eed      __eed
#define _eec      __eec.byte

#define _dmbp0    __bp.bits.__dmbp0
#define _stis     __muxsel.bits.__stis
#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _clksel0  __pscr.bits.__clksel0
#define _clksel1  __pscr.bits.__clksel1
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _wrf      __rstfc.bits.__wrf
#define _lvrf     __rstfc.bits.__lvrf
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _vbgen    __lvdc.bits.__vbgen
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _ints0    __integ.bits.__ints0
#define _ints1    __integ.bits.__ints1
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _isgen    __idata.bits.__isgen
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _umd      __simc0.bits.__umd
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _utx8     __uucr1.bits.__utx8
#define _urx8     __uucr1.bits.__urx8
#define _utxbrk   __uucr1.bits.__utxbrk
#define _ustops   __uucr1.bits.__ustops
#define _uprt     __uucr1.bits.__uprt
#define _upren    __uucr1.bits.__upren
#define _ubno     __uucr1.bits.__ubno
#define _uren     __uucr1.bits.__uren
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _sima0    __sima.bits.__sima0
#define _sima1    __sima.bits.__sima1
#define _sima2    __sima.bits.__sima2
#define _sima3    __sima.bits.__sima3
#define _sima4    __sima.bits.__sima4
#define _sima5    __sima.bits.__sima5
#define _sima6    __sima.bits.__sima6
#define _uteie    __uucr2.bits.__uteie
#define _utiie    __uucr2.bits.__utiie
#define _urie     __uucr2.bits.__urie
#define _uwake    __uucr2.bits.__uwake
#define _uadden   __uucr2.bits.__uadden
#define _ubrgh    __uucr2.bits.__ubrgh
#define _urxen    __uucr2.bits.__urxen
#define _utxen    __uucr2.bits.__utxen
#define _utxrx0   __utxr_rxr.bits.__utxrx0
#define _utxrx1   __utxr_rxr.bits.__utxrx1
#define _utxrx2   __utxr_rxr.bits.__utxrx2
#define _utxrx3   __utxr_rxr.bits.__utxrx3
#define _utxrx4   __utxr_rxr.bits.__utxrx4
#define _utxrx5   __utxr_rxr.bits.__utxrx5
#define _utxrx6   __utxr_rxr.bits.__utxrx6
#define _utxrx7   __utxr_rxr.bits.__utxrx7
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _ubrg0    __ubrg.bits.__ubrg0
#define _ubrg1    __ubrg.bits.__ubrg1
#define _ubrg2    __ubrg.bits.__ubrg2
#define _ubrg3    __ubrg.bits.__ubrg3
#define _ubrg4    __ubrg.bits.__ubrg4
#define _ubrg5    __ubrg.bits.__ubrg5
#define _ubrg6    __ubrg.bits.__ubrg6
#define _ubrg7    __ubrg.bits.__ubrg7
#define _utxif    __uusr.bits.__utxif
#define _utidle   __uusr.bits.__utidle
#define _urxif    __uusr.bits.__urxif
#define _uridle   __uusr.bits.__uridle
#define _uoerr    __uusr.bits.__uoerr
#define _uferr    __uusr.bits.__uferr
#define _unf      __uusr.bits.__unf
#define _uperr    __uusr.bits.__uperr
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _emi      __intc0.bits.__emi
#define _inte     __intc0.bits.__inte
#define _opde     __intc0.bits.__opde
#define _ade      __intc0.bits.__ade
#define _intf     __intc0.bits.__intf
#define _opdf     __intc0.bits.__opdf
#define _adf      __intc0.bits.__adf
#define _stmpe    __intc1.bits.__stmpe
#define _stmae    __intc1.bits.__stmae
#define _lve      __intc1.bits.__lve
#define _dee      __intc1.bits.__dee
#define _stmpf    __intc1.bits.__stmpf
#define _stmaf    __intc1.bits.__stmaf
#define _lvf      __intc1.bits.__lvf
#define _def      __intc1.bits.__def
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _usime    __intc2.bits.__usime
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _usimf    __intc2.bits.__usimf
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _strp0    __stmc0.bits.__strp0
#define _strp1    __stmc0.bits.__strp1
#define _strp2    __stmc0.bits.__strp2
#define _ston     __stmc0.bits.__ston
#define _stck0    __stmc0.bits.__stck0
#define _stck1    __stmc0.bits.__stck1
#define _stck2    __stmc0.bits.__stck2
#define _stpau    __stmc0.bits.__stpau
#define _stcclr   __stmc1.bits.__stcclr
#define _stdpx    __stmc1.bits.__stdpx
#define _stpol    __stmc1.bits.__stpol
#define _stoc     __stmc1.bits.__stoc
#define _stio0    __stmc1.bits.__stio0
#define _stio1    __stmc1.bits.__stio1
#define _stm0     __stmc1.bits.__stm0
#define _stm1     __stmc1.bits.__stm1
#define _opdsw0   __opdswa.bits.__opdsw0
#define _opdsw1   __opdswa.bits.__opdsw1
#define _opdsw2   __opdswa.bits.__opdsw2
#define _opdsw3   __opdswa.bits.__opdsw3
#define _opdsw4   __opdswa.bits.__opdsw4
#define _opdsw5   __opdswa.bits.__opdsw5
#define _opdsw6   __opdswa.bits.__opdsw6
#define _opdsw7   __opdswa.bits.__opdsw7
#define _opdsw8   __opdswb.bits.__opdsw8
#define _opdsw9   __opdswb.bits.__opdsw9
#define _opdsw10  __opdswb.bits.__opdsw10
#define _opdsw11  __opdswb.bits.__opdsw11
#define _opdsw12  __opdswb.bits.__opdsw12
#define _opdsw13  __opdswb.bits.__opdsw13
#define _opdsw14  __opdswb.bits.__opdsw14
#define _opdsw15  __opdswb.bits.__opdsw15
#define _opdsw16  __opdswc.bits.__opdsw16
#define _opdsw17  __opdswc.bits.__opdsw17
#define _opdsw18  __opdswc.bits.__opdsw18
#define _opdsw19  __opdswc.bits.__opdsw19
#define _opdsw20  __opdswc.bits.__opdsw20
#define _opdsw21  __opdswc.bits.__opdsw21
#define _opdsw22  __opdswc.bits.__opdsw22
#define _opdsw23  __opdswc.bits.__opdsw23
#define _opdsw24  __opdswd.bits.__opdsw24
#define _opdsw25  __opdswd.bits.__opdsw25
#define _opdsw26  __opdswd.bits.__opdsw26
#define _opdsw27  __opdswd.bits.__opdsw27
#define _opdsw28  __opdswd.bits.__opdsw28
#define _opddeb0  __opdc0.bits.__opddeb0
#define _opddeb1  __opdc0.bits.__opddeb1
#define _opddeb2  __opdc0.bits.__opddeb2
#define _opdints0 __opdc0.bits.__opdints0
#define _opdints1 __opdc0.bits.__opdints1
#define _opdcen   __opdc0.bits.__opdcen
#define _opda0en  __opdc0.bits.__opda0en
#define _opda1en  __opdc0.bits.__opda1en
#define _opda0bw  __opdc1.bits.__opda0bw
#define _opda1bw  __opdc1.bits.__opda1bw
#define _opdis0   __opdc1.bits.__opdis0
#define _opdis1   __opdc1.bits.__opdis1
#define _opdhys0  __opdc1.bits.__opdhys0
#define _opdhys1  __opdc1.bits.__opdhys1
#define _opd0o    __opdc1.bits.__opd0o
#define _opd1o    __opdc1.bits.__opd1o
#define _opda0of0 __opda0cal.bits.__opda0of0
#define _opda0of1 __opda0cal.bits.__opda0of1
#define _opda0of2 __opda0cal.bits.__opda0of2
#define _opda0of3 __opda0cal.bits.__opda0of3
#define _opda0of4 __opda0cal.bits.__opda0of4
#define _opda0of5 __opda0cal.bits.__opda0of5
#define _opda0rsp __opda0cal.bits.__opda0rsp
#define _opda0ofm __opda0cal.bits.__opda0ofm
#define _opda1of0 __opda1cal.bits.__opda1of0
#define _opda1of1 __opda1cal.bits.__opda1of1
#define _opda1of2 __opda1cal.bits.__opda1of2
#define _opda1of3 __opda1cal.bits.__opda1of3
#define _opda1of4 __opda1cal.bits.__opda1of4
#define _opda1of5 __opda1cal.bits.__opda1of5
#define _opda1rsp __opda1cal.bits.__opda1rsp
#define _opda1ofm __opda1cal.bits.__opda1ofm
#define _opdcof0  __opdccal.bits.__opdcof0
#define _opdcof1  __opdccal.bits.__opdcof1
#define _opdcof2  __opdccal.bits.__opdcof2
#define _opdcof3  __opdccal.bits.__opdcof3
#define _opdcof4  __opdccal.bits.__opdcof4
#define _opdcrsp  __opdccal.bits.__opdcrsp
#define _opdcofm  __opdccal.bits.__opdcofm
#define _opdcout  __opdccal.bits.__opdcout
#define _sacs0    __sadc0.bits.__sacs0
#define _sacs1    __sadc0.bits.__sacs1
#define _sacs2    __sadc0.bits.__sacs2
#define _sacs3    __sadc0.bits.__sacs3
#define _adrfs    __sadc0.bits.__adrfs
#define _adcen    __sadc0.bits.__adcen
#define _adbz     __sadc0.bits.__adbz
#define _start    __sadc0.bits.__start
#define _sacks0   __sadc1.bits.__sacks0
#define _sacks1   __sadc1.bits.__sacks1
#define _sacks2   __sadc1.bits.__sacks2
#define _sains0   __sadc1.bits.__sains0
#define _sains1   __sadc1.bits.__sains1
#define _sains2   __sadc1.bits.__sains2
#define _sains3   __sadc1.bits.__sains3
#define _pgags0   __sadc2.bits.__pgags0
#define _pgags1   __sadc2.bits.__pgags1
#define _savrs0   __sadc2.bits.__savrs0
#define _savrs1   __sadc2.bits.__savrs1
#define _pgais    __sadc2.bits.__pgais
#define _adpgaen  __sadc2.bits.__adpgaen
#define _scsbs0   __ifs.bits.__scsbs0
#define _scsbs1   __ifs.bits.__scsbs1
#define _rxsdisdas0 __ifs.bits.__rxsdisdas0
#define _rxsdisdas1 __ifs.bits.__rxsdisdas1
#define _sckscls0 __ifs.bits.__sckscls0
#define _sckscls1 __ifs.bits.__sckscls1
#define _eea0     __eea.bits.__eea0
#define _eea1     __eea.bits.__eea1
#define _eea2     __eea.bits.__eea2
#define _eea3     __eea.bits.__eea3
#define _eea4     __eea.bits.__eea4
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _BS45F3235_H_
